# ubuntu version
dist: bionic
# see https://docs.travis-ci.com/user/languages/python/
language: python
# python versions to be tested
python:
#  - "2.7" # see https://github.com/WolfgangFahl/gremlin-python-tutorial/issues/7
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
services:
  # allow launching docker
  - docker
  # allow gui output
  - xvfb
before_install:
  # check version
  - lsb_release -a
  - mkdir graphdata
  # start janusgraph
  - docker run -it -p 8182:8182 --mount src=$HOME/graphdata,target=/graphdata,type=bind janusgraph/janusgraph

# command to install python dependencies
install:
  - ./install

# command to run tests
script:
  - python3 -m unittest discover
