#!/bin/bash
os=$(uname -a)
case $os in
  Darwin*)
   pip="sudo -H pip"
   install="sudo port install"
   ;;
  *)
   pip="pip3"
   if [ "$USER" = "travis" ]
   then
     # https://stackoverflow.com/a/20621143/1497139
     echo "environment is travis with python version $TRAVIS_PYTHON_VERSION"
     pip="pip"
   fi
   install="sudo apt-get install"
   ;;
esac
$pip install -r requirements.txt
