#!/bin/bash
# WF 2020-04-03
# test
if [ ! -d $HOME/graphdata ]
then
  mkdir $HOME/graphdata
fi
# start janusgraph in docker image in background
rm nohup.out
nohup docker run -i -p 8182:8182 --mount src=$HOME/graphdata,target=/graphdata,type=bind janusgraph/janusgraph&
./install
./waitport gremlin-port localhost 8182
echo "waiting for janusgraph to be ready"
while  grep "started at port 8182" nohup.out > /dev/null
do
  sleep 1
  echo -n "."
done
python3 -m unittest discover
